---
title: "Comparison of randomization methods"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
params:
  NamedId: 
    value: 'C10'
---
# Setup
```{r setup, }
#clear
  knitr::opts_chunk$set(warning = F, message = F)
  source('P:\\flunm\\K1M\\flublok_pretrial\\flublok_pretrial_cfg.R')
```

### Brown University   
### School of Public Health   
### Center for Gerontology  
### PI: Vincent Mor  

*Project started:* `r prj.StDate`  
*Documented created* `r Sys.time()`   
*Programmer:* `r prj.coder`  

### Project Configuration:  
```{r config}
#--FileName Identifier
  NamedId <- params$NamedId
  
#--Pull FileNames from param
  FileNames <- Param$FileNames[Param$FileNames$CodeFileId==NamedId,]
  
#--CodeFileName  
  File.Dir.Src <- list.files(wd.CodeFiles, '.Rmd')
  File.Dir.Curr <- str_detect(File.Dir.Src, NamedId)
  CodeFileName <- File.Dir.Src[File.Dir.Curr]
```
#### Codefile Name:  (Confirm with title and directory file)  
Codefile: `r CodeFileName`

#### Used Files:  
```{r }
   tab_files(FileNames)
```



```{r, }
rm(params)
save.image(file='flublok_pretrial_sims.RData')
```